project:
  type: website

website:
  title: "Modelado de la Ocupación, abundancia y densidad de poblaciones"
  twitter-card: 
    creator: "@dlizcano"
    site: "https://github.com/dlizcano/occu_multi_season"
  site-url: "https://dlizcano.github.io/occu_multi_season"
  repo-url: "https://github.com/dlizcano/occu_multi_season"
  navbar:
    search: true
    right:
      - href: index.qmd
        text: Home
      - href: parte1.qmd
        text: parte1
      - href: parte2.qmd
        text: parte2
      - href: parte3.qmd
        text: parte3
      - href: about.qmd
      - icon: twitter
        href: https://twitter.com/dlizcano
      - icon: github
        href: https://github.com/dlizcano/occu_multi_season
        aria-label: GitHub
  comments:
    giscus:
      repo: dlizcano/occu_multi_season
      theme:
        light: light # giscus theme used for light website theme
        dark: dark_dimmed # giscus theme used for dark website theme

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

    
editor: visual

